### ISSUE TITLE
Question about MKL benchmarking methodology

### ISSUE THREAD

**Issue by marsupialtail** [vnatesh/CAKE_on_CPU#1]
The paper is very interesting. I have a question about the MKL benchmarking methodology.

Correct me if I am mistaken, but it appears you are measuring the runtime of a single invocation of cblas_sgemm. 

According to the official MKL guide, you need to ignore the time of the first invocation, and do repeated invocations to the kernel to ensure stable measurement times: https://www.intel.com/content/www/us/en/developer/articles/technical/a-simple-example-to-measure-the-performance-of-an-intel-mkl-function.html

Failure to do so could add massive overheads to the MKL runtime, especially for small matrices in multi-core settings.

**Comment by vnatesh** [comment]
Thank you for your interest in the paper. We measured the time of a single invocation but then averaged that time over several such calls. Both CAKE and MKL incur some overhead for initialization of buffers and we wanted to make an apples to apples comparison. 

In addition, the matrices we used are not necessarily "small". The minimum size tested was 1000x1000 matrices and Intel defines small matrices as matrices where the cube root of M*N*K is less than 128. Intel also has several optimizations for small matrices as shown in https://www.codeproject.com/Articles/1169319/Reducing-Packing-Overhead-in-Matrix-Matrix-Multipl and https://www.intel.com/content/www/us/en/developer/articles/technical/onemkl-improved-small-matrix-performance-using-just-in-time-jit-code.html. CAKE could also benefit from such optimizations.

I'd be happy to jump on a call with you to discuss this in more detail, or if you have any suggestions for improving the generalizability of the results.

**Comment by marsupialtail** [comment]
On my laptop, measuring the first invocation of cblas_sgemm on a 1024x1024x1024 matmul with 4 threads takes 80 milliseconds. Measuring just the *second* single invocation only takes 13 milliseconds. 

I see your point about apples to apples comparison though, that makes sense. 

Happy to discuss this over a call sometime.
